import os
import subprocess
import tempfile
from http.cookiejar import Cookie
from pathlib import Path
from typing import Iterable

import click

from yagent.api_client import api_request


YOUTUBE_URL = "https://www.youtube.com/"
DEFAULT_DOMAINS = ("youtube.com",)


def _cookie_applies(cookie: Cookie, domain: str) -> bool:
    cookie_domain = (cookie.domain or "").lstrip(".").lower()
    domain = domain.lstrip(".").lower()
    return cookie_domain == domain or cookie_domain.endswith(f".{domain}")


def _format_bool(value: bool) -> str:
    return "TRUE" if value else "FALSE"


def _browser_cookie3_to_netscape(browser: str, domains: Iterable[str]) -> str:
    import browser_cookie3

    loaders = {
        "chrome": browser_cookie3.chrome,
        "chromium": getattr(browser_cookie3, "chromium", None),
        "firefox": browser_cookie3.firefox,
        "edge": getattr(browser_cookie3, "edge", None),
        "safari": getattr(browser_cookie3, "safari", None),
    }
    loader = loaders.get(browser)
    if loader is None:
        raise click.ClickException(f"Unsupported browser for fallback: {browser}")

    lines = ["# Netscape HTTP Cookie File", "# Generated by y cookies sync"]
    seen: set[tuple[str, str, str]] = set()
    for domain in domains:
        jar = loader(domain_name=domain)
        for cookie in jar:
            if not _cookie_applies(cookie, domain) or not cookie.name:
                continue
            key = (cookie.domain, cookie.path, cookie.name)
            if key in seen:
                continue
            seen.add(key)
            include_subdomains = cookie.domain_initial_dot or cookie.domain.startswith(".")
            expires = int(cookie.expires or 0)
            lines.append("\t".join([
                cookie.domain,
                _format_bool(include_subdomains),
                cookie.path or "/",
                _format_bool(bool(cookie.secure)),
                str(expires),
                cookie.name,
                cookie.value or "",
            ]))
    return "\n".join(lines) + "\n"


def _extract_with_ytdlp(browser: str) -> str:
    fd, tmp_path = tempfile.mkstemp(prefix="y-cookies-", suffix=".txt")
    os.close(fd)
    Path(tmp_path).unlink(missing_ok=True)
    try:
        result = subprocess.run([
            "yt-dlp",
            "--cookies-from-browser", browser,
            "--cookies", tmp_path,
            "--skip-download",
            "--simulate",
            "--no-warnings",
            "--quiet",
            YOUTUBE_URL,
        ], capture_output=True, text=True, timeout=60)
        if result.returncode != 0:
            raise RuntimeError(result.stderr.strip() or "yt-dlp failed")
        path = Path(tmp_path)
        if not path.exists() or path.stat().st_size == 0:
            raise RuntimeError("yt-dlp did not write cookies")
        return path.read_text(encoding="utf-8")
    finally:
        Path(tmp_path).unlink(missing_ok=True)


def _filter_netscape(cookies_txt: str, domain: str) -> str:
    lines = ["# Netscape HTTP Cookie File", "# Generated by y cookies sync"]
    normalized = domain.lstrip(".").lower()
    for raw_line in cookies_txt.splitlines():
        line = raw_line.strip()
        if not line or (line.startswith("#") and not line.startswith("#HttpOnly_")):
            continue
        parts = line.split("\t")
        if len(parts) < 7:
            continue
        cookie_domain = parts[0].removeprefix("#HttpOnly_").lstrip(".").lower()
        if cookie_domain == normalized or cookie_domain.endswith(f".{normalized}"):
            lines.append(line)
    return "\n".join(lines) + "\n"


def _cookie_count(cookies_txt: str) -> int:
    return sum(
        1 for line in cookies_txt.splitlines()
        if line.strip()
        and (not line.startswith("#") or line.startswith("#HttpOnly_"))
        and len(line.split("\t")) >= 7
    )


@click.command(name="sync")
@click.option("--domain", "domains", multiple=True, default=DEFAULT_DOMAINS, show_default=True, help="Cookie domain to sync; repeatable.")
@click.option("--browser", default="chrome", show_default=True, help="Browser profile for cookie extraction.")
def cookies_sync(domains: tuple[str, ...], browser: str):
    """Sync local browser cookies to the y-agent API."""
    try:
        raw_cookies = _extract_with_ytdlp(browser)
    except Exception as exc:
        click.echo(f"yt-dlp cookie export failed ({exc}); falling back to browser_cookie3", err=True)
        raw_cookies = _browser_cookie3_to_netscape(browser, domains)

    for domain in domains:
        cookies_txt = _filter_netscape(raw_cookies, domain)
        count = _cookie_count(cookies_txt)
        if count == 0:
            raise click.ClickException(f"No cookies found for {domain}")
        resp = api_request("PUT", "/api/cookies", json={"domain": domain, "cookies_txt": cookies_txt})
        data = resp.json()
        click.echo(f"Synced {data.get('count', count)} cookies for {data.get('domain', domain)}")
