/*
 * Artifact build recipe for `y module publish` (lifted from spike-2412/build.mjs).
 *
 *   1. esbuild  : index.tsx -> ESM bundle, externals redirected to alias shims
 *   2. tailwind : generated CSS entry -> utilities-only stylesheet
 *                 (theme(reference) + source(none) + no preflight — F1/F2)
 *   3. scope    : wrap stylesheet so it cannot restyle host chrome (@scope)
 *   4. inline   : append `export const css = "…"` (decision D2)
 *   5. hash     : sha256 of the final bytes -> manifest.json
 *
 * Run (from the materialized SDK dir on the VM):
 *   node build.mjs --slug <slug> --src <module-ui-dir> --out <out-dir> [--scope=scope|prefix|none]
 */
import { build } from "esbuild";
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));

function arg(name, fallback = undefined) {
  const flag = process.argv.find((a) => a.startsWith(`${name}=`));
  if (flag) return flag.slice(name.length + 1);
  const idx = process.argv.indexOf(name);
  if (idx >= 0 && process.argv[idx + 1] && !process.argv[idx + 1].startsWith("-")) {
    return process.argv[idx + 1];
  }
  return fallback;
}

const slug = arg("--slug");
const srcDir = path.resolve(arg("--src", path.join(here, "..")));
const outDir = path.resolve(arg("--out", path.join(srcDir, ".build", slug || "out")));
const scopeMode = arg("--scope", "scope");
const contractPath = path.join(here, "contract.json");

if (!slug) {
  console.error("usage: node build.mjs --slug <slug> [--src <ui-dir>] [--out <out-dir>] [--scope=scope|prefix|none]");
  process.exit(2);
}

const tsxPath = path.join(srcDir, "index.tsx");
if (!fs.existsSync(tsxPath)) {
  console.error(`source not found: ${tsxPath}`);
  process.exit(1);
}

const contract = JSON.parse(fs.readFileSync(contractPath, "utf8"));
const minHostVersion = Number(contract.version) || 1;

fs.mkdirSync(outDir, { recursive: true });

// ---------------------------------------------------------------- 1. esbuild
const shim = (f) => path.join(here, "shims", f);
let result;
try {
  result = await build({
    entryPoints: [tsxPath],
    bundle: true,
    format: "esm",
    target: "es2022",
    jsx: "automatic",
    platform: "browser",
    write: false,
    logLevel: "silent",
    // Pin the working directory so path comments in the bundle (and thus the
    // content hash) do not depend on the caller's cwd. The Python CLI also
    // runs this script with cwd=sdk dir; absWorkingDir is belt-and-suspenders.
    absWorkingDir: here,
    alias: {
      react: shim("react.cjs"),
      "react-dom": shim("react-dom.cjs"),
      "react-dom/client": shim("react-dom-client.cjs"),
      "react/jsx-runtime": shim("react-jsx-runtime.cjs"),
      swr: shim("swr.cjs"),
      "swr/infinite": shim("swr-infinite.cjs"),
      recharts: shim("recharts.cjs"),
      "lightweight-charts": shim("lightweight-charts.cjs"),
      "@y/host": shim("y-host.cjs"),
    },
  });
} catch (err) {
  // esbuild puts a readable multi-line message on err.errors / err.message.
  const msg = err.errors
    ? err.errors.map((e) => `${e.location?.file || ""}:${e.location?.line || ""}: ${e.text}`).join("\n")
    : err.message || String(err);
  console.error(msg);
  process.exit(1);
}
const js = result.outputFiles[0].text;

// The load-bearing invariant: a blob: module cannot resolve bare specifiers.
const leftoverImports = [...js.matchAll(/^\s*(?:import|export)[^;]*?from\s*["']([^"']+)["']/gm)].map(
  (m) => m[1],
);
if (leftoverImports.length) {
  throw new Error(`bundle still imports external specifiers: ${leftoverImports.join(", ")}`);
}

// --------------------------------------------------------------- 2. tailwind
// Authors write ui/index.tsx and sibling files; the CSS entry is generated so
// the three D3 requirements (theme(reference), source(none), no preflight) cannot be forgotten.
// theme(reference) on the default theme import is MANDATORY (F1) or spacing /
// radius / text utilities silently vanish. source(none) is MANDATORY (F2) or
// Tailwind scans the whole VM home directory.
//
// The entry file must live under the SDK dir so `tailwindcss/theme.css` resolves
// via this package's node_modules (resolution walks from the CSS file, not --cwd).
const cacheDir = path.join(here, ".cache");
fs.mkdirSync(cacheDir, { recursive: true });
const cssEntry = path.join(cacheDir, `${slug}.entry.css`);
const tsxRel = path.relative(cacheDir, tsxPath).split(path.sep).join("/");
const partsDir = srcDir;
const partsRel = path.relative(cacheDir, partsDir).split(path.sep).join("/");
fs.writeFileSync(
  cssEntry,
  [
    "/* generated by y module publish — do not edit */",
    '@import "tailwindcss/theme.css" theme(reference);',
    '@import "tailwindcss/utilities.css" layer(utilities) source(none);',
    '@import "../theme.css";',
    `@source "${tsxRel.startsWith(".") ? tsxRel : `./${tsxRel}`}";`,
    // The full UI tree covers sibling parts below the canonical index entry.
    `@source "${partsRel.startsWith(".") ? partsRel : `./${partsRel}`}/**/*.{tsx,ts}";`,
    "",
  ].join("\n"),
);

const tailwindBin = path.join(here, "node_modules", ".bin", "tailwindcss");
if (!fs.existsSync(tailwindBin)) {
  console.error(`tailwindcss CLI not found at ${tailwindBin}; run: (cd ${here} && npm install)`);
  process.exit(1);
}

let cssRaw;
try {
  cssRaw = execFileSync(tailwindBin, ["-i", cssEntry, "--cwd", here], {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  });
} catch (err) {
  const stderr = err.stderr?.toString?.() || err.message || String(err);
  console.error(stderr);
  process.exit(1);
}

// ------------------------------------------------------------------ 3. scope
// `@property` is only valid at the top level — nesting it inside `@scope` gets
// the whole rule dropped, which silently breaks every `ring-*` / `shadow-*`
// utility (F3). Hoist those out before wrapping.
function hoistAtProperty(css) {
  const hoisted = [];
  const rest = css.replace(/@property\s+[^{]+\{[^}]*\}\s*/g, (m) => {
    hoisted.push(m.trim());
    return "";
  });
  return { hoisted: hoisted.join("\n"), rest };
}

function scopeCss(cssIn, artifactSlug, mode) {
  if (mode === "none") return cssIn;
  const { hoisted, rest: css } = hoistAtProperty(cssIn);
  if (mode === "scope") {
    // `@scope` adds no specificity, so artifact utilities stay peers of the
    // host's identical utilities instead of quietly outranking them.
    return `${hoisted}\n@scope ([data-y-artifact="${artifactSlug}"]) {\n${css}\n}\n`;
  }
  return `${hoisted}\n${prefixSelectors(css, artifactSlug)}\n`;
}

// `prefix` fallback: mechanical descendant-prefix on every top-level style rule.
// A regex cannot do this correctly — skip at-rule preludes, leave nested rules
// alone, ignore comments (brace walker from the spike).
function prefixSelectors(css, artifactSlug) {
  const out = [];
  let prelude = "";
  const stack = [];
  for (let i = 0; i < css.length; i++) {
    const ch = css[i];
    if (ch === "/" && css[i + 1] === "*") {
      const end = css.indexOf("*/", i + 2);
      out.push(css.slice(i, end + 2));
      i = end + 1;
      continue;
    }
    if (ch === "{") {
      const trimmed = prelude.trim();
      const isAtRule = trimmed.startsWith("@");
      const insideStyleRule = stack.some(Boolean);
      if (!isAtRule && !insideStyleRule) {
        const scoped = trimmed
          .split(",")
          .map((s) => `[data-y-artifact="${artifactSlug}"] ${s.trim()}`)
          .join(", ");
        out.push(prelude.slice(0, prelude.length - prelude.trimStart().length), scoped, " {");
      } else {
        out.push(prelude, "{");
      }
      stack.push(!isAtRule);
      prelude = "";
      continue;
    }
    if (ch === "}") {
      out.push(prelude, "}");
      stack.pop();
      prelude = "";
      continue;
    }
    if (ch === ";" && stack.length === 0) {
      out.push(prelude, ";");
      prelude = "";
      continue;
    }
    prelude += ch;
  }
  return out.join("") + prelude;
}

const css = scopeCss(cssRaw, slug, scopeMode);

// ----------------------------------------------------------------- 4. inline
const bundle = `${js}\nexport const css = ${JSON.stringify(css)};\nexport const slug = ${JSON.stringify(slug)};\nexport const minHostVersion = ${minHostVersion};\n`;

// ------------------------------------------------------------------- 5. hash
// source_digest covers the whole UI tree, so editing any sibling file changes
// this field. The bundle sha256 stays the integrity control, while source_digest
// reflects whether any source input changed.
function collectPartFiles(dir) {
  if (!fs.existsSync(dir)) return [];
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...collectPartFiles(full));
    else if (/\.(tsx|ts)$/.test(entry.name)) out.push(full);
  }
  return out.sort();
}

function computeSourceDigest(entryPath, partsDirPath) {
  const hash = createHash("sha256");
  hash.update(fs.readFileSync(entryPath));
  for (const file of collectPartFiles(partsDirPath)) {
    hash.update(fs.readFileSync(file));
  }
  return hash.digest("hex");
}

const bytes = Buffer.from(bundle, "utf8");
const sha256 = createHash("sha256").update(bytes).digest("hex");
const sourceDigest = computeSourceDigest(tsxPath, partsDir);

const bundlePath = path.join(outDir, `${slug}.js`);
const manifestPath = path.join(outDir, "manifest.json");
fs.writeFileSync(bundlePath, bytes);
fs.writeFileSync(
  manifestPath,
  JSON.stringify(
    {
      slug,
      sha256,
      source_digest: sourceDigest,
      min_host_version: minHostVersion,
      scope_mode: scopeMode,
      bytes: bytes.length,
      css_bytes: css.length,
      bundle: bundlePath,
    },
    null,
    2,
  ),
);

// Machine-readable one-liner for the Python CLI to parse.
process.stdout.write(
  JSON.stringify({
    slug,
    sha256,
    source_digest: sourceDigest,
    min_host_version: minHostVersion,
    bytes: bytes.length,
    bundle: bundlePath,
    manifest: manifestPath,
  }) + "\n",
);
